.TH titlecase 1 titlecase\-0.0.1
.SH NAME
titlecase \- !DESCRIPTION!
.SH SYNOPSIS
.B titlecase !USAGE!
.SH DESCRIPTION
.B titlecase
!WHAT IT DOES!
.SH OPTIONS
none
.SH EXAMPLES
.B titlecase 
!INVOCATIONS!
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
Copyright 2014 
.sp
You may use this software however you like.
