#!/usr/bin/env ruby

def tc_word(word)
  short_articles = ["a", "an", "the"]
  short_prepositions = ["on", "in", "to", "by", "for", "at", "of", "as", "off", "as", "out", "up" ]
  short_conjunctions = [ "and", "but", "nor", "or", "yet", "so" ]
  # write my own splitter to get rid of this punctuation junk? No... do as regex?
  abbrevs = ["re", "re:", "w/", "w", "etc.", "etc"]
  ignore = short_articles + short_prepositions + short_conjunctions + abbrevs

  case word
  when /[[:upper:]]/, *ignore
    word
  else
    word.sub(/^./){|first| first.upcase}
  end
end

loop { case ARGV[0]
  when /--/ then ARGV.shift; break
  when /^-/ then usage("Unknown option: #{ARGV[0].inspect}")
  else break
end; }

while gets() do
    line = $_.chomp
    tc_words =  line.split.map do |word|
      tc_word(word) 
    end
    puts tc_words.join(' ')
end   
